openapi: 3.0.0
info:
  title: API de Sistema de Facturación y Stock
  description: API para gestionar facturas, productos, clientes y proveedores.
  version: 1.0.0

servers:
  - url: https://localhost:8080/par2024

paths:
  /facturas:
    get:
      summary: Obtener todas las facturas
      responses:
        '200':
          description: Lista de facturas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factura'
        '500':
          description: Error interno del servidor
    post:
      summary: Crear una nueva factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '201':
          description: Factura creada correctamente
        '400':
          description: Datos inválidos en la solicitud
        '500':
          description: Error interno del servidor

  /facturas/{id}:
    get:
      summary: Obtener una factura por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Factura obtenida correctamente
        '404':
          description: Factura no encontrada
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar una factura por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura actualizada correctamente
        '400':
          description: Datos inválidos en la solicitud
        '404':
          description: Factura no encontrada
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar una factura por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Factura eliminada correctamente
        '404':
          description: Factura no encontrada
        '500':
          description: Error interno del servidor

  /productos:
    get:
      summary: Obtener todos los productos en stock
      responses:
        '200':
          description: Lista de productos obtenida correctamente
        '500':
          description: Error interno del servidor
    post:
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado correctamente
        '400':
          description: Datos inválidos en la solicitud
        '500':
          description: Error interno del servidor

  /productos/{id}:
    get:
      summary: Obtener un producto por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto obtenido correctamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar un producto por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado correctamente
        '400':
          description: Datos inválidos en la solicitud
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un producto por su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Producto eliminado correctamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

  /clientes:
    get:
      summary: Obtener todos los clientes
      responses:
        '200':
          description: Lista de clientes obtenida correctamente
        '500':
          description: Error interno del servidor
    post:
      summary: Crear un nuevo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente creado correctamente
        '400':
          description: Datos inválidos en la solicitud
        '500':
          description: Error interno del servidor

  /proveedores:
    get:
      summary: Obtener todos los proveedores registrados
      responses:
        '200':
          description: Lista de proveedores obtenida correctamente
        '500':
          description: Error interno del servidor
    post:
      summary: Crear un nuevo proveedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proveedor'
      responses:
        '201':
          description: Proveedor creado correctamente
        '400':
          description: Datos inválidos en la solicitud
        '500':
          description: Error interno del servidor

components:
  schemas:
    Factura:
      type: object
      properties:
        id:
          type: integer
        numero:
          type: string
        cliente:
          type: string
        total:
          type: number
      required:
        - numero
        - cliente
        - total
    Producto:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        precio:
          type: number
        descripcion:
          type: string
      required:
        - nombre
        - precio
    Cliente:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        email:
          type: string
      required:
        - nombre
        - email
    Proveedor:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        telefono:
          type: string
      required:
        - nombre
        - telefono
